version: "3.7"

services:

  serve:
    command: mkdocs serve -a 0.0.0.0:8080
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
    - "./:/home"
    ports:
    - "8080:8080"

  deploy:
    command: mkdocs gh-deploy
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
    - "./:/home"
    ports:
    - "8080:8080"
