site_name: Alohomora
markdown_extensions:
  - codehilite
nav:
- Início: 'index.md'
- Projeto:
  - 'Documento de visão': 'projeto/doc_visao.md'
  - 'Documento de arquitetura': 'projeto/doc_arquitetura.md'
  - 'Guia de uso': 'projeto/guia_de_uso.md'
- Gerência:
  - 'Termo de abertura do projeto': 'gerencia/TAP.md'
  - 'Estrutura analítica do projeto': 'gerencia/EAP.md'
  - 'Plano de gerenciamento de riscos': 'gerencia/plano_riscos.md'
  - 'Plano de gerencimaneto de custos': 'gerencia/plano_custos.md'
- Sprints:
  - 'Sprint 1': 'sprints/sprint_1.md'
  - 'Sprint 2': 'sprints/sprint_2.md'
  - 'Sprint 3': 'sprints/sprint_3.md'
  - 'Sprint 4': 'sprints/sprint_4.md'
  - 'Sprint 5': 'sprints/sprint_5.md'
  - 'Sprint 6': 'sprints/sprint_6.md'

theme: material
